<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-03-09 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 3334e8a579b79091e8a0c5885998cb91548e0b34


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('products', '0005_alter_category_id_alter_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_category_id_alter_product_id'),
>>>>>>> 3334e8a579b79091e8a0c5885998cb91548e0b34
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
<<<<<<< HEAD
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
=======
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
>>>>>>> 3334e8a579b79091e8a0c5885998cb91548e0b34
        ),
    ]
