# Generated by Django 6.0.2 on 2026-03-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('products', '0005_alter_category_id_alter_product_id'),
    ]

    operations = [
    ]
